name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: make setup
    - name: Test
      run: make check