name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: Install dependencies
      run: |
        sudo apt-get update &&
        sudo apt-get install \
          libxml2-utils \
          python3-venv \
          xsltproc
    - name: Checkout code
      uses: actions/checkout@v2
      run: |
        git fetch --tags --all
    - name: Setup
      run: make setup
    - name: Test
      run: make check
